# -*- coding: utf-8 -*-
"""05_cluster_3d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlDLlvymcR4nB_lszcnZ680Qz61Jj-Aq
"""

import math

A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)

# Input tuple
U = eval(input("Masukkan titik U dalam bentuk tuple (x1, x2, x3): "))

def jarak(p1, p2):
    return math.sqrt(sum((p1[i] - p2[i])**2 for i in range(3)))

dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)

if dA <= dB and dA <= dC:
    print("Titik U termasuk Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U termasuk Cluster B")
else:
    print("Titik U termasuk Cluster C")

import math

A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)

# Input tuple
U = eval(input("Masukkan titik U dalam bentuk tuple (x1, x2, x3): "))

def jarak(p1, p2):
    return math.sqrt(sum((p1[i] - p2[i])**2 for i in range(3)))

dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)

if dA <= dB and dA <= dC:
    print("Titik U termasuk Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U termasuk Cluster B")
else:
    print("Titik U termasuk Cluster C")

import math

A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)

# Input tuple
U = eval(input("Masukkan titik U dalam bentuk tuple (x1, x2, x3): "))

def jarak(p1, p2):
    return math.sqrt(sum((p1[i] - p2[i])**2 for i in range(3)))

dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)

if dA <= dB and dA <= dC:
    print("Titik U termasuk Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U termasuk Cluster B")
else:
    print("Titik U termasuk Cluster C")

import math

A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)

# Input tuple
U = eval(input("Masukkan titik U dalam bentuk tuple (x1, x2, x3): "))

def jarak(p1, p2):
    return math.sqrt(sum((p1[i] - p2[i])**2 for i in range(3)))

dA = jarak(U, A)
dB = jarak(U, B)
dC = jarak(U, C)

if dA <= dB and dA <= dC:
    print("Titik U termasuk Cluster A")
elif dB <= dA and dB <= dC:
    print("Titik U termasuk Cluster B")
else:
    print("Titik U termasuk Cluster C")