# -*- coding: utf-8 -*-
"""05_cluster_3d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131b9R7Rm6jvcaxUUa2-NkVxoSO_iWa7i
"""

import math

# Fungsi untuk menghitung jarak Euclidean
def hitung_jarak(P, Q):
    return math.sqrt(
        (P[0] - Q[0])**2 +
        (P[1] - Q[1])**2 +
        (P[2] - Q[2])**2
    )

# Fungsi untuk menentukan cluster
def tentukan_cluster(x1, x2, x3):
    # Titik pusat cluster
    A = (2, 1, 3)
    B = (1, -4, 6)
    C = (-2, 3, -2)

    # Titik yang akan diklasifikasikan
    U = (x1, x2, x3)

    # Menghitung jarak ke masing-masing cluster
    dA = hitung_jarak(U, A)
    dB = hitung_jarak(U, B)
    dC = hitung_jarak(U, C)

    # Menentukan cluster terdekat
    if dA <= dB and dA <= dC:
        cluster = "A"
    elif dB <= dA and dB <= dC:
        cluster = "B"
    else:
        cluster = "C"

    return cluster

# Program utama
x1 = float(input("Masukkan x1: "))
x2 = float(input("Masukkan x2: "))
x3 = float(input("Masukkan x3: "))

hasil = tentukan_cluster(x1, x2, x3)

print("Titik U termasuk Cluster", hasil)